# Generated by Django 5.2.16 on 2026-08-16 13:37

import django.db.models.deletion
import duediligence.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0009_property_listing_intent_property_listing_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KhataLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('khata_number', models.CharField(max_length=10)),
                ('unique_gata_id', models.CharField(blank=True, max_length=50)),
                ('fetch_status', models.CharField(choices=[('ok', 'OK'), ('not_found', 'Not Found'), ('error', 'Error')], max_length=10)),
                ('fetch_error_message', models.TextField(blank=True)),
                ('raw_report_html', models.TextField(blank=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='MutationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('raw_text', models.TextField()),
                ('case_number', models.CharField(blank=True, max_length=100)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('khata_number_in_entry', models.CharField(blank=True, max_length=10)),
                ('khasra_numbers_in_entry', models.CharField(blank=True, max_length=100)),
                ('area_text', models.CharField(blank=True, max_length=200)),
                ('seller_name', models.CharField(blank=True, max_length=200)),
                ('buyer_name', models.CharField(blank=True, max_length=200)),
                ('deed_amount_text', models.CharField(blank=True, max_length=100)),
                ('deed_date', models.DateField(blank=True, null=True)),
                ('is_litigation_flagged', models.BooleanField(default=False)),
                ('matched_litigation_keywords', models.CharField(blank=True, max_length=255)),
                ('khata_lookup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutation_entries', to='duediligence.khatalookup')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='TitleCheckReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(blank=True, max_length=100)),
                ('district_code', models.CharField(blank=True, max_length=20)),
                ('tehsil_name', models.CharField(blank=True, max_length=100)),
                ('tehsil_code', models.CharField(blank=True, max_length=20)),
                ('village_name', models.CharField(blank=True, max_length=150)),
                ('village_code', models.CharField(blank=True, max_length=20)),
                ('pargana_name', models.CharField(blank=True, max_length=100)),
                ('pargana_code', models.CharField(blank=True, max_length=20)),
                ('deed_date', models.DateField(blank=True, null=True)),
                ('consideration_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('seller_name', models.CharField(blank=True, max_length=200)),
                ('buyer_name', models.CharField(blank=True, max_length=200)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('book_number', models.CharField(blank=True, max_length=50)),
                ('volume_number', models.CharField(blank=True, max_length=50)),
                ('page_number', models.CharField(blank=True, max_length=50)),
                ('deed_area_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deed_area_unit', models.CharField(choices=[('sqm', 'Sq. Metres (matches Bhulekh)'), ('sqft', 'Sq. Ft.'), ('nali', 'Nali'), ('bigha', 'Bigha')], default='sqm', max_length=10)),
                ('deed_pdf', models.FileField(blank=True, help_text='Optional — kept for audit reference only, not parsed automatically.', null=True, storage=duediligence.models.deed_pdf_storage, upload_to='duediligence/deeds/%Y/%m/')),
                ('status', models.CharField(choices=[('draft', 'Draft — Not Yet Checked'), ('complete', 'Check Complete'), ('failed', 'Check Failed')], default='draft', max_length=10)),
                ('risk_level', models.CharField(choices=[('green', 'Green — Clean Match'), ('yellow', 'Yellow — Review Needed'), ('orange', 'Orange — Partial/Unreliable Result'), ('red', 'Red — Mismatch Found'), ('gray', 'Gray — Lookup Failed')], default='gray', max_length=10)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title_check_reports', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='khatalookup',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khata_lookups', to='duediligence.titlecheckreport'),
        ),
        migrations.CreateModel(
            name='KhasraEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('khasra_number', models.CharField(help_text='e.g. 409, or 409M / 123/2 for sub-divided plots.', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('lookup_status', models.CharField(choices=[('pending', 'Not Yet Checked'), ('found', 'Found'), ('not_found', 'No Record Found'), ('error', 'Lookup Error')], default='pending', max_length=10)),
                ('lookup_error_message', models.TextField(blank=True)),
                ('matched_khata_number', models.CharField(blank=True, max_length=10)),
                ('latest_mutation_case_number', models.CharField(blank=True, max_length=100)),
                ('latest_mutation_order_date', models.DateField(blank=True, null=True)),
                ('latest_mutation_seller_name', models.CharField(blank=True, max_length=200)),
                ('latest_mutation_buyer_name', models.CharField(blank=True, max_length=200)),
                ('latest_mutation_area_text', models.CharField(blank=True, max_length=200)),
                ('latest_mutation_deed_amount_text', models.CharField(blank=True, max_length=100)),
                ('latest_mutation_deed_date', models.DateField(blank=True, null=True)),
                ('latest_mutation_raw_text', models.TextField(blank=True)),
                ('area_match', models.BooleanField(blank=True, null=True)),
                ('seller_match', models.BooleanField(blank=True, null=True)),
                ('buyer_match', models.BooleanField(blank=True, null=True)),
                ('khata_lookup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='khasra_entries', to='duediligence.khatalookup')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khasra_entries', to='duediligence.titlecheckreport')),
            ],
            options={
                'verbose_name_plural': 'khasra entries',
                'ordering': ['order', 'id'],
            },
        ),
    ]
