# Generated by Django 5.2.16 on 2026-08-16 14:05

import duediligence.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duediligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='titlecheckreport',
            name='extracted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='titlecheckreport',
            name='extraction_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='titlecheckreport',
            name='extraction_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='titlecheckreport',
            name='extraction_raw_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='titlecheckreport',
            name='extraction_status',
            field=models.CharField(choices=[('not_attempted', 'Not Attempted'), ('complete', 'Extraction Complete'), ('error', 'Extraction Failed')], default='not_attempted', max_length=15),
        ),
        migrations.AlterField(
            model_name='titlecheckreport',
            name='deed_pdf',
            field=models.FileField(blank=True, help_text='Optional — attach to audit-trail the deed, and to enable "Extract with AI".', null=True, storage=duediligence.models.deed_pdf_storage, upload_to='duediligence/deeds/%Y/%m/'),
        ),
    ]
