# Generated by Django 5.2.16 on 2026-09-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duediligence', '0002_titlecheckreport_extracted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titlecheckreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft — Not Yet Checked'), ('queued', 'Bhulekh Check Queued'), ('complete', 'Check Complete'), ('failed', 'Check Failed')], default='draft', max_length=10),
        ),
    ]
