# Generated by Django 5.2.16 on 2026-09-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duediligence', '0003_alter_titlecheckreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='khasraentry',
            name='amount_match',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='khasraentry',
            name='buyer_match_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='khasraentry',
            name='date_match',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='khasraentry',
            name='seller_match_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
