# Generated by Django 5.2.16 on 2026-08-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertyvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='area_unit',
            field=models.CharField(choices=[('sqft', 'Sq. Ft.'), ('gaj', 'Gaj'), ('nali', 'Nali'), ('bigha', 'Bigha'), ('acre', 'Acre')], default='sqft', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='region',
            field=models.CharField(choices=[('maldevta', 'Maldevta'), ('dehradun', 'Dehradun'), ('dhanaulti', 'Dhanaulti'), ('mussoorie', 'Mussoorie'), ('sahastradhara', 'Sahastradhara')], max_length=20),
        ),
    ]
