# Generated by Django 5.2.16 on 2026-08-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_area_unit_alter_property_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('plot', 'Plot'), ('flat', 'Flat'), ('villa', 'Villa'), ('farmhouse', 'Farmhouse')], max_length=10),
        ),
    ]
