# Generated by Django 5.2.16 on 2026-08-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Leave blank for 'Price on Request' — shows Call/WhatsApp links instead.", max_digits=12, null=True),
        ),
    ]
