# Generated by Django 5.2.16 on 2026-08-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('plot', 'Plot'), ('land', 'Land / Zameen'), ('flat', 'Flat'), ('villa', 'Villa'), ('farmhouse', 'Farmhouse')], max_length=10),
        ),
    ]
