# Generated by Django 5.2.16 on 2026-08-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='region',
            field=models.CharField(choices=[('maldevta', 'Maldevta'), ('dehradun', 'Dehradun'), ('dhanaulti', 'Dhanaulti'), ('mussoorie', 'Mussoorie'), ('sahastradhara', 'Sahastradhara'), ('garhwal', 'Garhwal'), ('thano', 'Thano'), ('rishikesh', 'Rishikesh')], max_length=20),
        ),
    ]
