# Generated by Django 5.2.16 on 2026-08-02 11:47

import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_property_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyvideo',
            name='video',
            field=models.FileField(storage=properties.models.video_storage, upload_to='properties/videos/%Y/%m/'),
        ),
    ]
