# Generated by Django 5.2.16 on 2026-08-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_propertyvideo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listing_intent',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], default='sale', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_source',
            field=models.CharField(choices=[('admin', 'Added by Admin'), ('seller', 'Submitted by Seller')], default='admin', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='moderation_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending Review'), ('rejected', 'Rejected')], default='approved', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='seller_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='property',
            name='seller_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='seller_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('plot', 'Plot'), ('land', 'Land / Zameen'), ('flat', 'Flat'), ('villa', 'Villa'), ('farmhouse', 'Farmhouse'), ('house', 'Independent House')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['moderation_status'], name='properties__moderat_61a0e1_idx'),
        ),
    ]
