# Generated by Django 5.2.16 on 2026-08-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_listing_intent_property_listing_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('maldevta', 'Maldevta'), ('dehradun', 'Dehradun'), ('dhanaulti', 'Dhanaulti'), ('mussoorie', 'Mussoorie'), ('sahastradhara', 'Sahastradhara'), ('garhwal', 'Garhwal'), ('thano', 'Thano'), ('rishikesh', 'Rishikesh')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text="Shown on the homepage locations section and this region's landing page. Leave blank until real copy is ready — the region still appears, just without a description.")),
                ('image', models.ImageField(blank=True, help_text='Leave blank until a real photograph is available — falls back to a plain placeholder rather than a stock image.', null=True, upload_to='locations/')),
            ],
            options={
                'ordering': ['region'],
            },
        ),
    ]
