# Generated by Django 5.2.16 on 2026-08-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_seed_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.TextField(blank=True, help_text='Free text, one per line — only shown if filled in.'),
        ),
        migrations.AddField(
            model_name='property',
            name='land_use',
            field=models.CharField(blank=True, help_text='e.g. "Residential", "Agricultural".', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='ownership',
            field=models.CharField(blank=True, choices=[('freehold', 'Freehold'), ('leasehold', 'Leasehold'), ('power_of_attorney', 'Power of Attorney'), ('cooperative_society', 'Cooperative Society')], max_length=25),
        ),
        migrations.AddField(
            model_name='property',
            name='registry_status',
            field=models.CharField(blank=True, help_text='e.g. "Registry Ready", "Registry in Process".', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='road_width',
            field=models.CharField(blank=True, help_text='e.g. "20 ft" — leave blank if unknown.', max_length=100),
        ),
    ]
