# Generated by Django 5.2.16 on 2026-08-19 02:23

import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_property_amenities_property_land_use_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, help_text='Leave blank until a real photograph is available — falls back to a plain placeholder rather than a stock image.', null=True, upload_to='locations/', validators=[properties.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='properties/%Y/%m/', validators=[properties.models.validate_image_size]),
        ),
    ]
