# Generated by Django 5.2.16 on 2026-09-20 11:05

import django.db.models.deletion
import investment.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0013_alter_location_image_alter_propertyimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('property_type', models.CharField(blank=True, choices=[('plot', 'Plot'), ('land', 'Land / Zameen'), ('flat', 'Flat'), ('villa', 'Villa'), ('farmhouse', 'Farmhouse'), ('house', 'Independent House')], help_text='Leave blank to apply to every property type.', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldOverrideLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('previous_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='override_logs', to='investment.analysisrun')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyComparable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('area_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_unit', models.CharField(choices=[('sqft', 'Sq. Ft.'), ('gaj', 'Gaj'), ('nali', 'Nali'), ('bigha', 'Bigha'), ('acre', 'Acre')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('transaction_date', models.DateField(blank=True, help_text='Listing or transaction date, whichever is known.', null=True)),
                ('is_verified_transaction', models.BooleanField(default=False, help_text='False = listing price (unverified). True = a confirmed actual transaction — never treat these two as equivalent when computing a valuation range.')),
                ('source', models.CharField(blank=True, max_length=200)),
                ('source_url', models.URLField(blank=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('similarity_notes', models.TextField(blank=True)),
                ('confidence', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparables', to='investment.analysisrun')),
                ('property_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparables', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('sale_deed', 'Sale Deed'), ('registry', 'Registry'), ('khasra', 'Khasra'), ('khatauni', 'Khatauni'), ('mutation', 'Mutation Document'), ('land_use', 'Land-Use Document'), ('noc', 'NOC'), ('rera', 'RERA Document'), ('builder_approval', 'Builder Approval'), ('site_plan', 'Site Plan'), ('layout_plan', 'Layout Plan'), ('property_tax', 'Property Tax Document'), ('encumbrance', 'Encumbrance Document'), ('identity_ownership', 'Identity / Ownership Document'), ('other', 'Other Supporting Document')], max_length=25)),
                ('file', models.FileField(storage=investment.models.property_document_storage, upload_to='investment/documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verification_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('extracted', 'Extracted'), ('analyzed', 'Analyzed'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('needs_review', 'Needs Review')], default='uploaded', max_length=15)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('analysis_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='investment.analysisrun')),
                ('property_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.property')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim', models.TextField(help_text='e.g. "Property area is 150 gaj".')),
                ('source_type', models.CharField(choices=[('fact', 'Fact — Source-Backed'), ('ai_analysis', 'AI Analysis — Interpretation'), ('estimate', 'Estimate — Model/Calculation'), ('unverified', 'Unverified — Requires Human Verification')], max_length=15)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True)),
                ('extracted_value', models.TextField(blank=True)),
                ('confidence', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('disputed', 'Disputed')], default='unverified', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='investment.analysisrun')),
                ('property_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='properties.property')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_items', to='investment.propertydocument')),
            ],
            options={
                'verbose_name_plural': 'evidence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_text', models.TextField(blank=True)),
                ('extracted_data', models.JSONField(blank=True, default=dict, help_text='Structured fields, schema-validated before being stored here.')),
                ('raw_ai_response', models.TextField(blank=True, help_text="Audit trail — the model's raw response JSON.")),
                ('extraction_method', models.CharField(blank=True, max_length=50)),
                ('confidence', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('flagged_inconsistencies', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='investment.propertydocument')),
            ],
            options={
                'verbose_name_plural': 'document analyses',
            },
        ),
        migrations.CreateModel(
            name='PropertyRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('legal', 'Legal'), ('price', 'Price'), ('location', 'Location'), ('developer', 'Developer'), ('document', 'Document'), ('liquidity', 'Liquidity'), ('infrastructure', 'Infrastructure'), ('environmental', 'Environmental'), ('market', 'Market'), ('data_quality', 'Data Quality')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical'), ('unknown', 'Unknown')], max_length=10)),
                ('reason', models.TextField()),
                ('recommended_verification', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='investment.analysisrun')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='investment.evidence')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('median_comparable_price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lower_range_price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('upper_range_price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('asking_price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('premium_discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('comparable_count', models.PositiveSmallIntegerField(default=0)),
                ('methodology_notes', models.TextField(blank=True)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('analysis_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valuation', to='investment.analysisrun')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_scores', models.JSONField(blank=True, default=dict, help_text='e.g. {"legal_documentation": 72, "price_valuation": 81, ...} — each 0-100.')),
                ('overall_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('confidence_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('missing_data_penalty_applied', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True, help_text='Human-readable explanation of why the score is what it is — never just the number.')),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('analysis_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='investment.analysisrun')),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='investment.scoringconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, choices=[('ownership', 'Ownership'), ('title_documentation', 'Title / Documentation'), ('land_classification', 'Land Classification'), ('land_use', 'Land-Use'), ('registry', 'Registry'), ('encumbrance', 'Encumbrance'), ('litigation', 'Litigation Indicators'), ('noc_approval', 'NOC / Approval'), ('rera_compliance', 'RERA / Project Compliance'), ('road_access', 'Road / Access'), ('utilities', 'Utilities'), ('location', 'Location'), ('developer', 'Developer / Builder'), ('market_price', 'Market Price'), ('liquidity', 'Liquidity'), ('property_condition', 'Property Condition'), ('environmental', 'Environmental / Geographical Risk')], max_length=25)),
                ('is_required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('not_applicable', 'Not Applicable')], default='pending', max_length=15)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_items', to='investment.analysisrun')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DueDiligenceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ownership', 'Ownership'), ('title_documentation', 'Title / Documentation'), ('land_classification', 'Land Classification'), ('land_use', 'Land-Use'), ('registry', 'Registry'), ('encumbrance', 'Encumbrance'), ('litigation', 'Litigation Indicators'), ('noc_approval', 'NOC / Approval'), ('rera_compliance', 'RERA / Project Compliance'), ('road_access', 'Road / Access'), ('utilities', 'Utilities'), ('location', 'Location'), ('developer', 'Developer / Builder'), ('market_price', 'Market Price'), ('liquidity', 'Liquidity'), ('property_condition', 'Property Condition'), ('environmental', 'Environmental / Geographical Risk')], max_length=25)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('warning', 'Warning'), ('unknown', 'Unknown'), ('not_applicable', 'Not Applicable'), ('pending_verification', 'Pending Verification')], default='unknown', max_length=25)),
                ('notes', models.TextField(blank=True)),
                ('verification_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_diligence_checks', to='investment.analysisrun')),
            ],
            options={
                'ordering': ['category'],
                'constraints': [models.UniqueConstraint(fields=('analysis_run', 'category'), name='one_check_per_category_per_run')],
            },
        ),
        migrations.CreateModel(
            name='ScoringFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('legal_documentation', 'Legal / Documentation'), ('price_valuation', 'Price / Valuation'), ('location', 'Location'), ('infrastructure', 'Infrastructure'), ('market', 'Market'), ('liquidity', 'Liquidity'), ('property_quality', 'Property Quality')], max_length=25)),
                ('weight_percent', models.DecimalField(decimal_places=2, help_text="This category's weight, 0-100. All factors in one configuration should sum to 100.", max_digits=5)),
                ('risk_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='investment.scoringconfiguration')),
            ],
            options={
                'ordering': ['category'],
                'constraints': [models.UniqueConstraint(fields=('configuration', 'category'), name='one_factor_per_category_per_configuration')],
            },
        ),
    ]
