# Generated by Django 5.2.16 on 2026-09-20 11:48

import investment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydocument',
            name='file',
            field=models.FileField(storage=investment.models.property_document_storage, upload_to='investment/documents/%Y/%m/', validators=[investment.models.validate_document_file]),
        ),
    ]
